blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog/', views.blog, name='blog'),
    path('article/<int:pk>/<str:slug>/', views.article, name='article'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from os import getenv
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from django.views.i18n import set_language


urlpatterns = [
    path(getenv("ADMIN_URL") + '/', admin.site.urls),
    path('', include('info.urls')),
    path('', include('shop.urls')),
    path('', include('blog.urls')),
]


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
    
    
urlpatterns += i18n_patterns(
    *urlpatterns,
    prefix_default_language=True,
)


urlpatterns += [
    path("i18n/", include("django.conf.urls.i18n")),
]

    

    

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    



admin.site.index_title = _("SCUBO - İdarəetmə Paneli")
admin.site.site_title = _("SCUBO - İdarəetmə Paneli")
admin.site.site_header = _("SCUBO - İdarəetmə Paneli")

info/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'info'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('products/', views.products, name='products'),
    path('product/<int:pk>/<str:slug>', views.product_detail, name='product-detail'),
]

templates/about.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}


{% block title %}

<title>{% trans "Scubo - Haqqımızda" %}</title>

{% endblock title %}


{% block main %}


<section class="page-header">
  <div class="page-header__bg" style="
        background-image: url({% static "assets/images/background/footer-bg-1-1.jpg" %});
      "></div>
  <!-- /.page-header__bg -->
  <div class="container">
    <ul class="list-unstyled thm-breadcrumb">
      <li><a href="{% url "info:home" %}">{% trans "Ana səhifə" %}</a></li>
      <li class="active"><a href="#">{% trans "Haqqımızda" %}</a></li>
    </ul>
    <!-- /.list-unstyled -->
    <h2 class="page-header__title">{% trans "Haqqımızda" %}</h2>
    <!-- /.page-header__title -->
  </div>
  <!-- /.container -->
</section>
<!-- /.page-header -->

<section class="about-two">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 d-flex about-two__content-wrapper">
        <div class="my-auto">
          <div class="about-two__content">
            <div class="block-title text-left">
              <img src="{% static "assets/images/shapes/sec-line-1.png" %}" alt="" />
              <p class="text-uppercase">{% trans "Our benefits" %}</p>
              <h3 class="text-uppercase">
                {{about.title}}
              </h3>
            </div>
            <!-- /.block-title -->
            <div class="about-desc">
              <p>{{about.description|linebreaks}}</p>
            </div>

            <!-- <ul class="list-unstyled about-two__list">
              <li>
                <span class="about-two__list-count"></span>
                All the lorem ipsum generators on the Internet
              </li>
              <li>
                <span class="about-two__list-count"></span>
                When an unknown printer took a galley
              </li>
              <li>
                <span class="about-two__list-count"></span>
                Various versions have evolved years
              </li>
            </ul> -->
            <!-- /.list-unstyled about-two__list -->
          </div>
          <!-- /.about-two__content -->
        </div>
        <!-- /.my-auto -->
      </div>
      <!-- /.col-lg-6 -->
      <div class="col-lg-6">
        <div class="about-two__image wow fadeInRight" data-wow-duration="1500ms">
          <img src="{{about.image.url}}" alt="" />
        </div>
        <!-- /.about-two__image -->
      </div>
      <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->
</section>
<!-- /.about-two -->

<section class="video-one">
  <div class="video-one__bg" style="
        background-image: url({% static "assets/images/background/video-bg-2-1.jpg" %});
      "></div>
  <!-- /.video-one__bg -->
  <div class="container text-center">
    <a href="{{about_video.url}}" class="video-popup"><i class="fa fa-play"></i></a>
    <!-- /.video-popup -->
    <h3>
      {{about_video.title}}
    </h3>
  </div>
  <!-- /.container -->
</section>
<!-- /.video-one -->



<div class="team-brand__wrapper" style="
      background-image: url({% static "assets/images/shapes/about-brand-team-bg.png" %});
    ">

  <section class="about-brand brand-one brand-one__home-one">
    <div class="container">
      <div class="block-title text-center">
        <h3 class="text-uppercase">{% trans "Partnyorlar" %}</h3>
      </div>
      <div class="brand-one__carousel owl-carousel thm__owl-carousel owl-theme"
        data-options='{"loop": true, "autoplay": true, "autoplayHoverPause": true, "autoplayTimeout": 1000, "items": 6, "dots": false, "nav": true, "margin": 30, "smartSpeed": 700, "responsive": { "0": {"items": 2, "margin": 30}, "480": {"items": 3, "margin": 30}, "991": {"items": 4, "margin": 50}, "1199": {"items": 6, "margin": 20}}}'>

        {% for partner in partners %}

      <div class="item">
        <img src="{{partner.image.url}}" alt="{{partner.title}}" />
      </div>
      
      {% endfor %}
      
      </div>

      <!-- /.brand-one__carousel owl-carousel thm__owl-carousel owl-theme -->
    </div>
    <!-- /.container -->
  </section>
  <!-- /.brand-one -->

  <!-- /.brand-one -->
</div>


{% endblock main %}

templates/contact.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}


{% block title %}

<title>{% trans "Scubo - Əlaqə" %}</title>

{% endblock title %}


{% block main %}

    <section class="contact-one">
      <img src="{% static "assets/images/shapes/fish-contact-1.png" %}" class="contact-one__fish" alt="" />
      <img src="{% static "assets/images/shapes/tree-contact-1.png" %}" class="contact-one__tree" alt="" />
      <img src="{% static "assets/images/shapes/swimmer-contact-1.png" %}" class="contact-one__swimmer" alt="" />
      <div class="container">
        <div class="row">
          <div class="col-xl-4">
            <div class="contact-one__content">
              <h3> {% trans "Bizimlə əlaqə" %} </h3>
              <div class="site-footer__bottom">
                <div class="container">
                  <div class="row">
                    <div class="col-lg-12">
                      <a href="tel:{{contact_info.phone}}"><i class="fa fa-phone-alt"></i><span>{{contact_info.phone}}</span></a>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-12">
                      <a href="mailto:{{contact_info.mail}}"><i
                          class="fa fa-envelope"></i><span>{{contact_info.mail}}</span></a>
                    </div>
                    <!-- /.col-lg-4 -->
                    <div class="col-lg-12">
                      <a href="#"><i class="fa fa-map"></i>{{contact_info.address}}</a>
                    </div>
                    <!-- /.col-lg-4 -->
                  </div>

                  <!-- /.row -->
                </div>

                <!-- /.container -->
              </div>
              <div class="footer-widget__social contact-one__social">
                <a href="{% if social_media.facebook %}{{social_media.facebook}}{% else %}#{% endif %}"><i class="fab fa-facebook-square"></i></a>
                <a href="{% if social_media.twitter %}{{social_media.twitter}}{% else %}#{% endif %}"><i class="fab fa-twitter"></i></a>
                <a href="{% if social_media.youtube %}{{social_media.youtube}}{% else %}#{% endif %}"><i class="fab fa-youtube"></i></a>
                <a href="{% if social_media.instagram %}{{social_media.instagram}}{% else %}#{% endif %}"><i class="fab fa-instagram"></i></a>
                <a href="{% if social_media.tiktok %}{{social_media.tiktok}}{% else %}#{% endif %}"><i class="fa-brands fa-tiktok"></i></a>
                <a href="{% if social_media.whatsapp %}{{social_media.whatsapp}}{% else %}#{% endif %}"><i class="fab fa-whatsapp"></i></a>
                <a href="{% if social_media.linkedin %}{{social_media.linkedin}}{% else %}#{% endif %}"><i class="fab fa-linkedin"></i></a>
              </div>
              <!-- /.contact-one__social -->
            </div>
            <!-- /.contact-one__content -->
          </div>
          <!-- /.col-xl-4 -->
          <div class="col-xl-8">
            {% if result == "success" %}
              <div class="col-xl-12" style="border: 1px solid green; background-color: green; margin-bottom: 20px; padding: 2rem">
                <p>{% trans "Müraciət uğurla göndərildi!" %}</p>
              </div>
            {% elif result == "fail" %}
              <div class="col-xl-12" style="border: 1px solid red; background-color: red; margin-bottom: 20px; padding: 2rem">
                <p>{% trans "Müraciətin göndərilməsində səhvlik oldu!" %}</p>
              </div>
            {% endif %}
            <form method="POST" action="{% url "info:contact" %}"
              class="contact-one__form contact-form-validated">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  {{form.full_name}}
                </div>
                <!-- /.col-md-6 -->
                <div class="col-md-6">
                  {{form.email}}
                </div>
                <!-- /.col-md-6 -->
                <div class="col-md-6">
                  {{form.phone}}
                </div>
                <!-- /.col-md-6 -->
                <div class="col-md-6">
                  {{form.subject}}
                </div>
                <!-- /.col-md-6 -->

                <!-- /.col-md-12 -->
                <div class="col-md-12">
                  {{form.message}}
                </div>
                <!-- /.col-md-12 -->
                <div class="col-md-12">
                  <button type="submit" class="thm-btn contact-one__btn">
                    {% trans "Mesajınızı göndər" %}
                  </button>
                </div>
                <!-- /.col-md-12 -->
              </div>
              <!-- /.row -->
            </form>
            <!-- /.contact-one__form -->
            <!-- /.result -->
          </div>
          <!-- /.col-xl-8 -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container -->
    </section>
    <!-- /.contact-one -->

    <!-- /.cta-one -->

    <div class="energy-map">
      <iframe
        src="{{contact_info.map_link}}"
        width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>



{% endblock main %}

templates/news-details.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}



{% block title %}

<title>{{article.title}}</title>

{% endblock title %}



{% block main %}
      <section class="page-header">
        <div
          class="page-header__bg"
          style="
            background-image: url({% static "assets/images/background/footer-bg-1-1.jpg" %});
          "
        ></div>
        <!-- /.page-header__bg -->
        <div class="container">
          <ul class="list-unstyled thm-breadcrumb">
            <li><a href="{% url "info:home" %}">{% trans "Ana Səhifə" %}</a></li>
            <li><a href="{% url "blog:blog" %}">{% trans "Xəbərlər" %}</a></li>
            <li class="active"><a href="#">{% trans "Xəbərlərin Detalları" %}</a></li>
          </ul>
          <!-- /.list-unstyled -->
          <h2 class="page-header__title">{% trans "Xəbərlərin Detalları" %}</h2>
          <!-- /.page-header__title -->
        </div>
        <!-- /.container -->
      </section>
      <!-- /.page-header -->

      <section class="blog-details">
        <div class="container">
          <div class="row">
            <div class="col-lg-8">
              <div class="blog-details__main">
                <div class="blog-one__image">
                  <a href="{% url "blog:article" pk=article.pk slug=article.slug %}" class="blog-one__date"
                    >{{article.created.date|date:"d F Y"}}</a
                  >
                  <div class="blog-one__image-inner">
                    <img src="{{article.image.url}}" alt="" />
                  </div>
                  <!-- /.blog-one__image-inner -->
                </div>
                <!-- /.blog-one__image -->
                <div class="blog-details__content">
                  <h3 class="blog-details__main-title">
                    {{article.title}}
                  </h3>
                  <p>
                    {{article.description|linebreaks}}
                  </p>
                </div>
                <!-- /.blog-details__content -->
                <div class="blog-details__content-bottom">
                  <div class="row">
                      {% for image in gallery %}
                      
                      <div class="col-lg-4 col-md-6">
                        <div class="gallery-one__single">
                          <img src="{{image.image.url}}" alt="" />
                          <a
                            href="{{image.image.url}}"
                            class="img-popup"
                            ><i class="scubo-icon-plus-symbol"></i
                          ></a>
                        </div>
                        <!-- /.gallery-one__single -->
                      </div>
                      
                      {% endfor %}
                  </div>
                  <!-- /.blog-details__tags -->
             
                  <!-- /.footer-widget__social -->
                </div>
                <!-- /.blog-details__content-bottom -->
              </div>
              <!-- /.blog-details__main -->
            </div>
            <!-- /.col-lg-8 -->
            <div class="col-lg-4">
              <div class="sidebar">
                <div class="sidebar__single sidear__search">
                  <form action="#" class="sidebar__search-form">
                    <input type="text" placeholder="{% trans "Axtar..." %}" />
                    <button type="submit">
                      <i class="scubo-icon-magnifying-glass"></i>
                    </button>
                  </form>
                  <!-- /.sidebar__search-form -->
                </div>
                <!-- /.sidebar__single sidear__search -->

                <!-- /.sidebar__single  -->
                <div class="sidebar__single sidebar__post">
                  <h3 class="sidebar__title">{% trans "Ən Son Məqalələr" %}</h3>
                  <!-- /.sidebar__title -->
                  <ul class="sidebar__post-list list-unstyled">
                    {% for article in last_articles %}
                    <li>
                      <img src="{{article.image.url}}" alt="" />
                      <h3>
                        <a href="{% url "blog:article" pk=article.pk slug=article.slug %}"
                          >{{article.title}}</a
                        >
                      </h3>
                    </li>
                    {% endfor %}
                  </ul>
                  <!-- /.sidebar__post-list list-unstyled -->
                </div>
                <!-- /.sidebar__single  -->
              </div>
              <!-- /.sidebar -->
            </div>
            <!-- /.col-lg-4 -->
          </div>
          <!-- /.row -->
        </div>
        <!-- /.container -->
      </section>
      <!-- /.blog-details -->
      
{% endblock main %}

templates/news.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load urlhelper %}
{% load i18n %}


{% block title %}

<title>{% trans "Scubo - Blog" %}</title>

{% endblock title %}


{% block main %}
      <section class="page-header">
        <div
          class="page-header__bg"
          style="
            background-image: url({% static "assets/images/background/footer-bg-1-1.jpg" %});
          "
        ></div>
        <!-- /.page-header__bg -->
        <div class="container">
          <ul class="list-unstyled thm-breadcrumb">
            <li><a href="{% url "info:home" %}">{% trans "Ana Səhifə" %}</a></li>
            <li class="active"><a href="#">{% trans "Xəbərlər" %}</a></li>
          </ul>
          <!-- /.list-unstyled -->
          <h2 class="page-header__title">{% trans "Son Xəbərlər" %}</h2>
          <!-- /.page-header__title -->
        </div>
        <!-- /.container -->
      </section>
      <!-- /.page-header -->

      <section class="blog-one">
        <div class="container">
          <div class="row">
            {% for article in articles %}
            
            <div class="col-lg-4 col-md-12">
              <div class="blog-one__single">
                <div class="blog-one__image">
                  <a href="{% url "blog:article" pk=article.pk slug=article.slug %}" class="blog-one__date"
                    >{{ article.created.date|date:"d F Y" }}</a
                  >
                  <div class="blog-one__image-inner">
                    <img src="{{article.image.url}}" alt="" />
                    <a href="{% url "blog:article" pk=article.pk slug=article.slug %}"
                      ><i class="scubo-icon-plus-symbol"></i
                    ></a>
                  </div>
                  <!-- /.blog-one__image-inner -->
                </div>
                <!-- /.blog-one__image -->
                <div class="blog-one__content">
                  <h3>
                    <a href="{% url "blog:article" pk=article.pk slug=article.slug %}"
                      >{{article.title}}</a
                    >
                  </h3>
                  <div class="blog-one__p">
                    <p>
                      {{ article.description|truncatechars:100 }}
                    </p>
                  </div>
                  <div class="blog-one__meta">
                    <div class="thm-btn news-detail">
                      <a href="{% url "blog:article" pk=article.pk slug=article.slug %}">{% trans "ətraflı" %}</a>
                    </div>
                  </div>
                  <!-- /.blog-one__meta -->
                </div>
                <!-- /.blog-one__content -->
              </div>
              <!-- /.blog-one__single -->
            </div>
            
            {% endfor %}
          </div>
          <!-- /.row -->
          <div class="post-pagination">
            {% if page.has_previous %}
              <a href="?{% edit_query request page=page.previous_page_number %}" class="post-pagination__prev">
                <i class="fa fa-angle-left"></i>
              </a>
            {% endif %}
  
  
            {% for page_number in paginator.page_range %}
  
            {% if page_number == page.number %}
              <a href="?{% edit_query request page=page_number %}" class="active">{{page_number}}</a>
            {% else %}
              <a href="?{% edit_query request page=page_number %}">{{page_number}}</a>
            {% endif %}
  
            {% endfor %}
  
            {% if page.has_next %}
              <a href="?{% edit_query request page=page.next_page_number %}" class="post-pagination__next">
                <i class="fa fa-angle-right"></i>
              </a>
            {% endif %}
          </div>
          <!-- /.post-pagination -->
        </div>
        <!-- /.container -->
      </section>
      <!-- /.blog-one -->

      
{% endblock main %}

templates/product-details.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load i18n %}


{% block title %}

<title>{{product.title}}</title>

{% endblock title %}


{% block main %}
    <section class="page-header">
      <div class="page-header__bg" style="
            background-image: url({% static "assets/images/background/footer-bg-1-1.jpg" %});
          "></div>
      <!-- /.page-header__bg -->
      <div class="container">
        <ul class="list-unstyled thm-breadcrumb">
          <li><a href="{% url "info:home" %}">{% trans "Ana səhifə" %}</a></li>
          <li class="active"><a href="#">{% trans "Məhsul detalı" %}</a></li>
        </ul>
        <!-- /.list-unstyled -->
        <h2 class="page-header__title">{% trans "Məhsul detalı" %}</h2>
        <!-- /.page-header__title -->
      </div>
      <!-- /.container -->
    </section>
    <!-- /.page-header -->

    <section class="course-one">
      <div class="container">
        <div class="row product-details-area">
          <div class="col-lg-5 col-md-6">
            <div class="">
              <div class="blog__inner product-details ">
                <div style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff" class="swiper mySwiper2">
                  <div class="swiper-wrapper product-details">
                    {% for product_image in product_images %}
                      <div class="swiper-slide">
                        <img src="{{product_image.image.url}}" alt="" />
                      </div>
                    {% endfor %}
                  </div>
                  <div class="swiper-button-next"></div>
                  <div class="swiper-button-prev"></div>
                </div>
                <div thumbsSlider="" class="swiper mySwiper">
                  <div class="swiper-wrapper">
                    {% for product_image in product_images %}
                      <div class="swiper-slide">
                        <img src="{{product_image.image.url}}" alt="" />
                      </div>
                    {% endfor %}
                  </div>
                </div>


              </div>

            </div>
            <!-- /.course-one__single -->
          </div>
          <div class="col-lg-7 col-md-6">
            <h3 class="blog-details__main-title">
              {{product.title}}
            </h3>
            <div>
              <a>{{product.category.title}}</a>
            </div>
            <div class="price-area">
              {% if product.price != 0 %}
                <div> {% trans "Qiymət" %}:<span class="price">{{product.price}}</span> ₼</div>
              {% else %}
                <div>{% trans "Qiymət" %}: <span>{% trans "Razılaşma yolu ilə" %}</span> </div>
              {% endif %}
              
            </div>
            <div class="details-desc">
              <p>{{product.description}}</p>
            </div>
            <div class="wp-link">
              <a href="https://api.whatsapp.com/send?phone={{phone_number}}&text={{wp_message}}" target="_blank"><i class="fab fa-whatsapp"></i>
                {{contact_info.phone}}</a>
            </div>
          </div>
        </div>
        <!-- /.row -->

      </div>
      <!-- /.container -->
    </section>
    <!-- /.course-one -->


    <!-- RELATED PRODUCTS STARS -->

    <div class="course-one course-one__carousel-wrapper related-products">
      <!-- footer fishes -->
      <img src="{% static "assets/images/shapes/fish-1-1.png" %}" alt="" class="site-footer__fish-1" />
      <!-- footer trees -->
      <img src="{% static "assets/images/shapes/tree-1-1.png" %}" class="site-footer__tree-1" alt="" />


      <div class="container">
        <div class="block-title text-center">
          <h3 class="text-uppercase">{% trans "Oxşar məhsullar" %}</h3>
        </div>
        <div class="course-one__carousel thm__owl-carousel owl-carousel owl-theme"
          data-options='{"loop": true,"items": , "margin":30, "smartSpeed": 700, "autoplay": true, "autoplayTimeout": 5000, "autoplayHoverPause": true, "nav": false, "dots": false, "responsive": { "0": {"items": 1}, "767": {"items": 2}, "991": {"items": 2}, "1199": { "items": 3} }}'
          data-carousel-prev-btn=".course-one__carousel-btn-left"
          data-carousel-next-btn=".course-one__carousel-btn-right">
          {% for sim_product in similar_products %}

          <div class="item">
            <div class="course-one__single">
              <div class="course-one__image">
                <a href="{% url "shop:product-detail" pk=sim_product.pk slug=sim_product.slug %}" class="course-one__cat">{{sim_product.category.title}}</a>
                <div class="course-one__image-inner">
                  <img src="{{sim_product.images.first.image.url}}" alt="" />
                  <a href="{% url "shop:product-detail" pk=sim_product.pk slug=sim_product.slug %}"><i class="scubo-icon-plus-symbol"></i></a>
                </div>
                <!-- /.course-one__image-inner -->
              </div>
              <!-- /.course-one__image -->
              <div class="course-one__content hvr-sweep-to-bottom">
                <h3>
                  <a href="{% url "shop:product-detail" pk=sim_product.pk slug=sim_product.slug %}">{{sim_product.title}}</a>
                </h3>
                <div class="course-content">
                  <p>
                    {{sim_product.description|truncatechars:100}}
                  </p>
                </div>
              </div>
              <!-- /.course-one__content -->
              <a href="{% url "shop:product-detail" pk=sim_product.pk slug=sim_product.slug %}" class="course-one__book-link">{% trans "Ətraflı" %}</a>
            </div>
            <!-- /.course-one__single -->
          </div>

          {% endfor %}
        </div>
        <!-- /.course-one__carousel thm__owl-carousel owl-carousel owl-theme -->

        <div class="course-one__carousel-btn__wrapper">
          <a class="course-one__carousel-btn-left" href="#"><i class="fa fa-angle-left"></i></a>
          <a class="course-one__carousel-btn-right" href="#"><i class="fa fa-angle-right"></i></a>
        </div>
        <!-- /.course-one__carousel-btn__wrapper -->
      </div>
      <!-- /.container -->
    </div>
    <!-- /.course-one__carousel-wrapper -->
    <!-- RELATED PRODUCTS ENDS -->
    
{% endblock main %}

templates/products.html
{% extends 'layouts/layout.html' %}
{% load static %}
{% load urlhelper %}
{% load i18n %}



{% block title %}

<title>{% trans "Scubo - Məhsullar" %}</title>

{% endblock title %}



{% block main %}

    <section class="page-header">
      <div class="page-header__bg" style="
            background-image: url({% static "assets/images/background/footer-bg-1-1.jpg" %});
          "></div>
      <!-- /.page-header__bg -->
      <div class="container">
        <ul class="list-unstyled thm-breadcrumb">
          <li><a href="{% url "info:home" %}">{% trans "Ana səhifə" %}</a></li>
          <li class="active"><a href="#">{% trans "Məhsullar" %}</a></li>
        </ul>
        <!-- /.list-unstyled -->
        <h2 class="page-header__title">{% trans "Bütün məhsullar" %}</h2>
        <!-- /.page-header__title -->
      </div>
      <!-- /.container -->
    </section>
    <!-- /.page-header -->

    <section class="course-one">
      <div class="container">
        <div class="row">
          {% for product in products %}
          
          <div class="col-lg-4 col-md-6">
            <div class="course-one__single">
              <div class="course-one__image">
                <a href="{% url "shop:product-detail" pk=product.pk slug=product.slug %}" class="course-one__cat">{{product.category.title}}</a>
                <div class="course-one__image-inner">
                  <img src="{{product.images.first.image.url}}" alt="" />
                  <a href={% url "shop:product-detail" pk=product.pk slug=product.slug %}><i class="scubo-icon-plus-symbol"></i></a>
                </div>
                <!-- /.course-one__image-inner -->
              </div>
              <!-- /.course-one__image -->
              <div class="course-one__content hvr-sweep-to-bottom">
                <h3><a href={% url "shop:product-detail" pk=product.pk slug=product.slug %}>{{product.title}}</a></h3>
                <div class="course-content">
                  <p>
                    {{product.description}}
                  </p>
                </div>
              </div>
              <!-- /.course-one__content -->
              <a href={% url "shop:product-detail" pk=product.pk slug=product.slug %} class="course-one__book-link">{% trans "Ətraflı" %}</a>
            </div>
            <!-- /.course-one__single -->
          </div>

          {% endfor %}

        </div>
        <!-- /.row -->
        <div class="post-pagination">
          {% if page.has_previous %}
            <a href="?{% edit_query request page=page.previous_page_number %}" class="post-pagination__prev">
              <i class="fa fa-angle-left"></i>
            </a>
          {% endif %}


          {% for page_number in paginator.page_range %}

          {% if page_number == page.number %}
            <a href="?{% edit_query request page=page_number %}" class="active">{{page_number}}</a>
          {% else %}
            <a href="?{% edit_query request page=page_number %}">{{page_number}}</a>
          {% endif %}

          {% endfor %}

          {% if page.has_next %}
            <a href="?{% edit_query request page=page.next_page_number %}" class="post-pagination__next">
              <i class="fa fa-angle-right"></i>
            </a>
          {% endif %}
        </div>
        <!-- /.post-pagination -->
      </div>
      <!-- /.container -->
    </section>
    <!-- /.course-one -->

{% endblock main %}